version: "3"

services:
  gglass:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "./gglass_config:/config"
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      PORT: "3000"
