version: "3"

services:
  # Overkill Traefik configuration
  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      # Remove for production
      - "8080:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config-traefik:/config"
      - "./acme-traefik:/acme"
    command:
      # Listen for 80/443
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"

      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"

      # Config file provider
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"

      # Enable letsencrypt
      - "--certificatesResolvers.le.acme.email=${LETSENCRYPT_EMAIL:-}"
      - "--certificatesResolvers.le.acme.storage=/acme/acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"

      # Remove for production
      - "--api.insecure=true"
      - "--api.dashboard=true"
    labels:
      ## Some overkill extras
      # Https redirection middleware
      - "traefik.http.middlewares.httpsredirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.httpsredirect.redirectscheme.permanent=true"
